# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

name: Build Linux Kernel

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel Version'
        required: true
        default: 'master'

jobs:
  build_kernel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential flex bison libssl-dev libelf-dev

    - name: Download Linux Kernel
      run: git clone -b ${{inputs.kernel_version}} https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git


    - name: Build Linux Kernel
      run: |
        cd bpf-next
        make defconfig
        make -j$(nproc)

    - name: List Kernel Image
      run: ls -l bpf-next/arch/x86/boot/bzImage

    - name: Upload Kernel Image
      uses: actions/upload-artifact@main
      with:
        name: bzImage
        path: bpf-next/arch/x86/boot/bzImage
   
  

