# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

name: Test WSL

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test_wsl:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update WSL
      run: wsl --update

    - name: Download Ubuntu 24.04 Base Image
      run: Invoke-WebRequest -Uri https://cdimage.ubuntu.com/ubuntu-base/releases/24.04/release/ubuntu-base-24.04.1-base-amd64.tar.gz -OutFile ubuntu-base-24.04.1-base-amd64.tar.gz
      
    - name: Install Ubuntu 24.04 Base Image
      run: wsl --import Ubuntu-24.04 .\Ubuntu-24.04 .\ubuntu-base-24.04.1-base-amd64.tar.gz --version 2

    - name: Launch WSL
      run: |
        wsl echo "Hello from WSL"
        wsl cat /etc/os-release
        wsl uname -a
